/**
 * The strings of the screens whose components live in `app/library`, `app/shell`, `app/editor` and
 * `app/core/validation`, in one place, so a later i18n retrofit is a mechanical change. No i18n
 * framework and no locale switching yet — just named constants grouped by screen.
 *
 * Adding strings: a new screen keeps its own module beside its components (for example
 * `app/preview/preview-strings.ts`, `app/source/source-strings.ts`) exporting one `…_STRINGS`
 * object in this style, rather than appending a group here — two slices appending to this file at
 * once is how the tree got broken once. Groups that already live here stay here; reading is always
 * fine.
 */
import type {ScriptStatus} from './script.model';

export const EDITOR_STRINGS = {
  shell: {
    brand: 'SpeechRecorder script editor',
    homeLabel: 'Script editor home',
    breadcrumbLabel: 'Breadcrumb',
    separator: '/',
    scriptWord: 'script',
    saveState: 'All changes saved',
    warningLabel: 'Warnings',
    undo: 'Undo',
    redo: 'Redo',
    preview: 'Preview',
    publish: 'Publish',
    readOnlyReason: 'Read-only: publishing, saving and editing are disabled.',
  },

  library: {
    title: 'Scripts',
    newScript: 'New script',
    importJson: 'Import JSON',
    importFailed: 'The file is not JSON, so nothing was imported:',
    exportJson: 'Export JSON',
    exportEmpty: 'This script has neither a draft nor a published version to export.',
    searchLabel: 'Search',
    searchPlaceholder: 'Name, id or itemcode',
    statusLabel: 'Status',
    statusAll: 'All',
    statusDrafts: 'Drafts',
    statusPublished: 'Published',
    statusArchived: 'Archived',
    loading: 'Loading scripts…',
    errorPrefix: 'The script list could not be loaded.',
    httpPrefix: 'HTTP',
    retry: 'Retry',
    empty: 'No scripts in this project yet. Create one or import a JSON file to get started.',
    caption: 'Scripts in this project',
    columnName: 'Name',
    columnSectionsItems: 'Sections / items',
    columnUpdated: 'Updated',
    columnStatus: 'Status',
    columnUsage: 'Usage',
    usageNone: '—',
    sessionsWord: 'sessions',
    versionPrefix: 'v',
    columnActions: 'Actions',
    idPrefix: '#',
    countSeparator: '·',
    plus: '+',
    sectionsWord: 'sections',
    drawnWord: 'drawn',
    updatedPlaceholder: '—',
    statusLabels: {
      DRAFT: 'Draft',
      PUBLISHED: 'Published',
      ARCHIVED: 'Archived',
    } satisfies Record<ScriptStatus, string>,
    edit: 'Edit',
    duplicate: 'Duplicate',
    archive: 'Archive',
    unarchive: 'Unarchive',
    noMatch: 'No script matches the filter.',
    legendLabel: 'What the statuses mean',
    legendDraftTitle: 'Draft',
    legendDraftBody: 'Changes not yet published. Only the editor sees them; sessions keep the published version.',
    legendPublishedTitle: 'Published',
    legendPublishedBody: 'A frozen version. Sessions created from it stay on it, even when the draft moves on.',
    legendInUseTitle: 'In use',
    legendInUseBody: 'Sessions have been recorded with this script. Publishing a new version does not touch them.',
  },

  // V1 appended its own group; `{placeholder}` slots are filled by `validation/interpolate.ts`.
  validation: {
    // E01–E11 (doc/script-editor/validation.md)
    e01: 'Itemcode is required.',
    e02: 'Another item already uses this itemcode.',
    e03NoBank: 'The item draws from a bank but no bank is chosen.',
    e03Missing: 'Bank {bankId} does not exist.',
    e04: 'The filter matches only {matchCount} items. Widen the filter or draw fewer.',
    e04Suspended: 'The filter match count is unknown because the bank could not be read. Count validation is suspended.',
    e05PrefixClash: 'Prefix {prefix} is already reserved at {path}.',
    e05Reserved: 'Itemcodes {prefix}001\u2013{prefix}{last} are reserved by the bank source at {path}.',
    e05PrefixMissing: 'A drawn itemcode prefix is required.',
    e06: 'The item plays media but no file is chosen.',
    e07: 'The item shows nothing and plays nothing.',
    e09Count: 'count must be a positive whole number.',
    e09Timing: '{field} must be a positive number of milliseconds.',
    e10: 'A script needs at least one section with one group.',
    e11Repeats: 'repeats must be at least 1.',
    e11NonNegative: '{field} must not be negative.',
    e11Height: 'The virtual view box height must be greater than zero.',
    e11Count: 'A drawn itemcode range holds at most 999 items.',

    // W01–W13
    w01: 'The section records automatically, but this item has no duration. The recording runs until the speaker presses Next.',
    w02: 'Image prompt has no alt text. Screen-reader users get no prompt, and lists show only the file name.',
    w03: 'Playing while recording captures the sound through the microphone unless headphones are required.',
    w04: '{withoutAudio} of the {matchCount} matching items have no model recording. Those items would appear without sound.',
    w05: 'The clip is {clip} ms but the pre-recording delay is {delay} ms, so recording starts while it still plays.',
    w05SuspendedMissing: 'The drawn items\u2019 clip durations are unknown because the bank could not be read. Playback timing validation is suspended.',
    w05SuspendedPartial: 'Some drawn items have no known clip duration. Playback timing validation is suspended.',
    w06: '{field} has no effect on this kind of item.',
    w07: 'Training items are exempt from the completeness check, so a draw here consumes bank items without producing required recordings.',
    w08: 'Only the first media item is shown by the recorder. The others are ignored.',
    w09: 'The speaker can replay without limit while the section advances on its own.',
    w10: 'This script needs recorder {required}; the deployment runs {actual}. Playback would be skipped silently.',
    w11Missing: '{src} is not in the project\u2019s media.',
    w11Suspended: '{src} cannot be checked because the project\u2019s media list could not be fetched.',
    w12: 'The item has no recording phase, so the clip plays at the wrong moment; use WITH_PROMPT, BEFORE or ONDEMAND.',
    w13: 'The item declares its placement twice; `playback` wins and the mediaitem flags are ignored.',

    // N01–N06
    n01: '{legacy} is read as the {modern} because {modern} is not set.',
    n02: 'The recorder does not implement RANDOMIZED and treats it as sequential.',
    n03: '{drawn} items are drawn per session, on top of {fixed} fixed items, so a session runs {total} items.',
    n04: 'This script now needs recorder {version} or newer, because it uses {feature}.',
    n05: 'A speaker-stable draw repeats the same items, so skipping what the speaker recorded can empty the draw.',
    n06: 'This section predates groups. The editor opens it read-only until it is converted, so saving never adds an empty `groups`.',
  },

  /** Editor screen chrome (ui-spec §3): loading/empty/error states and the read-only reason. */
  editor: {
    screenTitle: 'Script editor',
    loading: 'Loading script…',
    skeletonLabel: 'Loading the script outline…',
    loadErrorTitle: 'The draft could not be loaded',
    loadErrorBody: 'Editing is blocked until the draft loads. This is not an empty script.',
    startDraft: 'Start a draft from the published version',
    startDraftHint: 'This script has published versions but no draft — what the migration of an older store leaves behind. Starting a draft copies the newest published version, so nothing published changes.',
    retry: 'Retry',
    emptyTitle: 'This script has no sections',
    emptyBody: 'A script needs at least one section with one group before anything can be recorded.',
    addSection: 'Add section',
    scriptWord: 'Script',
    itemWord: 'Item',
    outlineRegion: 'Script outline',
    centreRegion: 'Script content',
    inspectorRegion: 'Inspector',
  },

  /** Outline column (ui-spec §3.1). */
  outline: {
    filterLabel: 'Filter',
    filterPlaceholder: 'Itemcode or prompt text',
    clearFilter: 'Clear filter',
    noMatch: 'No row matches the filter.',
    sectionLabel: 'Section {n}',
    sectionsCount: '{count} sections',
    groupLabel: 'Group {n}',
    itemsCount: '{count} items',
    drawnMarker: 'draws {count} from {bank}',
    drawnMarkerTitle: 'This group draws its items from a bank',
    training: 'Training',
    trainingTitle: 'This section is training, so its items are exempt from the completeness check',
    warning: 'Check',
    warningTitle: 'A check applies to this row',
    playsMedia: 'Plays media',
    playsMediaTitle: 'This item plays media',
    moveUp: 'Move up',
    moveDown: 'Move down',
    virtualScrollLabel: 'Script outline rows',
  },

  /** Centre column (ui-spec §3.2). */
  centre: {
    scriptHeading: 'Session flow',
    scriptIntro: 'One card per section. Select a card to open the section.',
    modeChip: {
      MANUAL: 'Manual',
      AUTOPROGRESS: 'Auto advance',
      AUTORECORDING: 'Auto record',
    },
    promptPhaseChip: {
      IDLE: 'Prompt: idle',
      PRERECORDING: 'Prompt: pre-recording',
      PRERECORDINGONLY: 'Prompt: pre-recording only',
      RECORDING: 'Prompt: recording',
    },
    counts: '{fixed} items + {drawn} drawn',
    trainingFlag: 'Training',
    playsMediaFlag: '{count} play media',
    cardSelect: 'Select section {n}',
    fixedGroupCaption: 'Fixed items',
    drawnGroupCaption: 'Drawn items',
    columns: {
      grip: 'Reorder',
      itemcode: 'Itemcode',
      prompt: 'Prompt',
      media: 'Media',
      kind: 'Kind',
      timing: 'Timing',
      warning: 'Check',
    },
    mediaText: 'Text',
    mediaPlaysFirst: 'Text + plays first',
    mediaPlaysOnDemand: 'Text + plays on demand',
    kindRecording: 'Recording',
    kindNonRecording: 'Information only',
    timingSentence: 'pre {pre} ms · rec {rec} · post {post} ms',
    recUnbounded: 'open',
    rowWarningTitle: 'A check applies to this item',
    drawnNoBank: 'This group draws from a bank, but no bank is chosen yet.',
    drawnNoBankHint: 'Choose a bank on the bank screen.',
    drawnUnknownBank: 'The bank could not be read, so the counts are unknown.',
    bankOriginProject: 'Project bank',
    bankOriginBuiltin: 'Ships with SpeechRecorder',
    matchCount: '{match} of {total} items match the filter',
    matchCountUnknown: 'match count unknown',
    filterWords: {
      category: 'category {value}',
      words: 'words {min}–{max}',
      minWords: 'at least {min} words',
      maxWords: 'at most {max} words',
      hasAudio: 'with a model recording',
      hasNoAudio: 'without a model recording',
      tags: 'tags {value}',
      q: 'text contains “{value}”',
      none: 'no filter: every item in the bank',
    },
    perSession: 'The draw happens once, at session creation, so every session gets its own selection.',
    perSpeaker: 'The draw happens once, at session creation, and a returning speaker gets the same items again.',
    perScript: 'The draw happens once per script version, so everyone recorded with this version gets the same items.',
    exampleTitle: 'Example draw',
    exampleNote: 'An example, not this session’s draw. The real draw is fixed when a session is created.',
    drawAnother: 'Draw another example',
    reservedCodes: 'Reserved codes {first}…{last}',
    openBank: 'Open the bank screen',
    exampleEmpty: 'The filter matches no item, so the example is empty.',
  },

  /** Inspector column (ui-spec §3.3) — the field map is the contract. */
  inspector: {
    script: {
      title: 'Script',
      id: 'Id',
      name: 'Name',
      virtualHeight: 'Image height (px)',
      counts: 'Counts',
      countsValue: '{sections} sections · {fixed} fixed items · {drawn} drawn per session',
      versionNote: 'Sessions stay on the version they were created with; a new publish does not move them.',
      historyTitle: 'Version history',
      historyEmpty: 'No published versions yet.',
      historyVersion: 'v{version}',
      historySessions: '{count} sessions',
      historyNote: 'Note',
      restore: 'Restore into the draft',
      openDraws: 'Resolved draws',
    },
    section: {
      title: 'Section',
      name: 'Name',
      modeLegend: 'Mode',
      modeHelp: {
        MANUAL: 'The operator starts and stops every item.',
        AUTOPROGRESS: 'The prompt advances on its own after each item.',
        AUTORECORDING: 'The recorder starts and finishes every take by itself.',
      },
      promptPhase: 'Prompt phase',
      promptPhaseHelp: {
        IDLE: 'The prompt is visible as soon as the item is selected.',
        PRERECORDING: 'The prompt appears when the pre-recording delay starts.',
        PRERECORDINGONLY: 'The prompt is visible only during the pre-recording delay.',
        RECORDING: 'The prompt stays hidden until recording starts.',
      },
      order: 'Order',
      orderSequential: 'Sequential',
      orderRandom: 'Random',
      orderRandomized: 'Randomized (the recorder ignores it)',
      training: 'Training',
      trainingHelp: 'Training items are exempt from the completeness check.',
      delete: 'Delete section',
    },
    group: {
      title: 'Group',
      kindLegend: 'Source',
      fixed: 'Fixed list',
      drawn: 'Drawn from bank',
      order: 'Order',
      itemCount: '{count} items',
      split: 'Split group',
      delete: 'Delete group',
      bank: 'Bank',
      bankProject: 'This project',
      bankBuiltin: 'Ships with SpeechRecorder',
      origin: 'Origin',
      filter: 'Filter',
      filterLink: 'Edit the filter on the bank screen',
      count: 'Items per session',
      countAgainst: 'matches {match} of {total} items',
      countUnknown: 'match count unknown; validation is suspended',
      fixedBy: 'Same items for',
      fixedBySESSION: 'Each session',
      fixedBySPEAKER: 'Each speaker',
      fixedBySCRIPT: 'Each script version',
      fixedByHelp: {
        SESSION: 'Every session draws its own items. Covers a large bank.',
        SPEAKER: 'A returning speaker gets the same items again. Suits repeated measurements.',
        SCRIPT: 'One draw per script version; everyone recorded with it gets the same items.',
      },
      skipRecorded: 'Skip what the speaker already recorded',
      skipRecordedHelp: 'Skipped items are refilled from the rest of the match, and the trace records that it happened.',
      prefix: 'Itemcode prefix',
      prefixPreview: 'Generated codes: {codes}',
      drawOnce: 'The draw is resolved once, at session creation.',
    },
    item: {
      title: 'Prompt item',
      itemcode: 'Itemcode',
      typeLegend: 'Kind',
      typeRecording: 'Recording',
      typeNonRecording: 'Information only',
      mediaSelect: 'Prompt media',
      mediaPlain: 'Plain text',
      mediaFormatted: 'Formatted text',
      mediaImage: 'Image',
      mediaNothing: 'Nothing on screen',
      text: 'Text',
      promptDoc: 'Formatted text',
      file: 'File',
      alt: 'Alt text',
      virtualHeight: 'Virtual height (px)',
      instructions: 'Instructions',
      preDelay: 'Pre-rec delay (ms)',
      recDuration: 'Rec duration (ms)',
      postDelay: 'Post-rec delay (ms)',
      displayDuration: 'Display duration (ms)',
    },
    playback: {
      legend: 'Media played to the speaker',
      empty: 'This item has no audio to play.',
      add: 'Add audio or video…',
      fileName: 'File',
      fileNone: 'No file chosen',
      duration: 'Duration',
      durationUnknown: 'unknown',
      audition: 'Audition',
      auditionNote: 'Preview only; nothing is recorded or uploaded.',
      remove: 'Remove',
      autoplay: 'Autoplay',
      replay: 'Replay',
      when: 'Plays',
      whenOptions: {
        WITH_PROMPT: 'With the prompt',
        BEFORE: 'Before the prompt',
        PRERECORDING: 'During the pre-recording delay',
        DURING: 'While recording',
        ONDEMAND: 'On request',
      },
      repeats: 'Repeats',
      gap: 'Gap (ms)',
      replayable: 'Replayable',
      maxReplays: 'Max replays',
      headphones: 'Requires headphones',
      w03: 'Playing while recording captures the sound through the microphone unless headphones are required.',
      canvasUnsupported: 'This browser cannot play this file here.',
    },
    timing: {
      legend: 'Timing',
      playbackSpan: 'Playback',
      preRecording: 'Pre-recording',
      recording: 'Recording',
      postRecording: 'After recording',
      onDemand: 'The clip plays on the speaker’s request.',
      openEnded: 'Open-ended',
      unbounded: 'The recording is open-ended, so it is hatched.',
      overMicrophone: 'The clip plays over an open microphone, so the recording is hatched.',
      previewLabel: 'Timeline preview',
      visibilityPrefix: 'Prompt visibility: ',
      visibility: {
        all: 'on the stage from the moment the item is selected.',
        from: 'on the stage from {phase} onward.',
        only: 'on the stage only during {phase}.',
        never: 'never on the stage for this item.',
      },
      phase: {
        SELECTED: 'selection',
        PRE_RECORDING: 'the pre-recording delay',
        RECORDING: 'recording',
        POST_RECORDING: 'the post-recording delay',
      },
    },
  },
} as const;
